In [3]:
import pandas as pd

In [4]:
df = pd.read_sas('/Users/karina/Documents/xplanar_placement/data/RXQ_RX_G.xpt', format='xport', encoding='utf-8')


df = df.assign(RXDDRUG=df['RXDDRUG'].str.split('; ')).explode('RXDDRUG').reset_index(drop=True)
df

          SEQN  RXDUSE          RXDDRUG RXDDRGID  RXQSEEN  RXDDAYS  RXDCOUNT
0      62161.0     1.0       FLUOXETINE   d00236      2.0   5840.0       2.0
1      62161.0     1.0  METHYLPHENIDATE   d00900      2.0   5840.0       2.0
2      62162.0     2.0                                NaN      NaN       NaN
3      62163.0     2.0                                NaN      NaN       NaN
4      62164.0     1.0        BUPROPION   d00181      2.0   9125.0       1.0
...        ...     ...              ...      ...      ...      ...       ...
20039  71914.0     1.0        ALBUTEROL   d04066      2.0   3285.0       1.0
20040  71914.0     1.0      IPRATROPIUM   d04066      2.0   3285.0       1.0
20041  71915.0     1.0        METFORMIN   d03807      2.0   1460.0       2.0
20042  71915.0     1.0       TAMSULOSIN   d04121      2.0    730.0       2.0
20043  71916.0     2.0                                NaN      NaN       NaN

[20044 rows x 7 columns]

In [6]:
top40 = df['RXDDRUG'].value_counts().head(40).index.tolist()[1:]

top40 = ['LISINOPRIL', 'SIMVASTATIN', 'METOPROLOL', 'METFORMIN', 'LEVOTHYROXINE',
       'AMLODIPINE', 'HYDROCHLOROTHIAZIDE', 'FUROSEMIDE', 'ATORVASTATIN',
       'OMEPRAZOLE', 'ATENOLOL', 'GLIPIZIDE', 'ALBUTEROL', 'WARFARIN',
       'ASPIRIN', 'POTASSIUM CHLORIDE', 'ESOMEPRAZOLE', 'CLOPIDOGREL',
       'CARVEDILOL', 'VALSARTAN', 'LOSARTAN', 'GABAPENTIN', 'ROSUVASTATIN',
       'LOVASTATIN', 'PIOGLITAZONE', 'PRAVASTATIN', 'RANITIDINE', 'TRAMADOL',
       'IBUPROFEN', 'INSULIN GLARGINE', 'CITALOPRAM', 'ALENDRONATE',
       'ALLOPURINOL', 'MONTELUKAST', 'FEXOFENADINE', 'TAMSULOSIN', 'ZOLPIDEM',
       'SERTRALINE', 'FLUTICASONE NASAL', 'PREDNISONE']

# Keep only top 40 drugs
filtered = df[df['RXDDRUG'].isin(top40)]

# Group by column SEQN and aggregate RXDDRUG
filtered = filtered.groupby('SEQN')['RXDDRUG'].apply(list).reset_index()

# remove less than 3 drugs in combination
filtered = filtered[filtered['RXDDRUG'].apply(len) >= 3]

In [11]:
# get unique values from RXDDRUG
unique_drugs = set()
for drugs in filtered['RXDDRUG']:
    unique_drugs.update(drugs)
unique_drugs = list(unique_drugs)

In [ ]:
top40

['LISINOPRIL',
 'SIMVASTATIN',
 'METOPROLOL',
 'METFORMIN',
 'LEVOTHYROXINE',
 'AMLODIPINE',
 'HYDROCHLOROTHIAZIDE',
 'FUROSEMIDE',
 'ATORVASTATIN',
 'OMEPRAZOLE',
 'ATENOLOL',
 'GLIPIZIDE',
 'ALBUTEROL',
 'WARFARIN',
 'ASPIRIN',
 'POTASSIUM CHLORIDE',
 'ESOMEPRAZOLE',
 'CLOPIDOGREL',
 'CARVEDILOL',
 'VALSARTAN',
 'LOSARTAN',
 'GABAPENTIN',
 'ROSUVASTATIN',
 'LOVASTATIN',
 'PIOGLITAZONE',
 'PRAVASTATIN',
 'RANITIDINE',
 'TRAMADOL',
 'IBUPROFEN',
 'INSULIN GLARGINE',
 'CITALOPRAM',
 'ALENDRONATE',
 'ALLOPURINOL',
 'MONTELUKAST',
 'FEXOFENADINE',
 'TAMSULOSIN',
 'ZOLPIDEM',
 'SERTRALINE',
 'FLUTICASONE NASAL',
 'PREDNISONE']

In [8]:
filtered

         SEQN                                            RXDDRUG
4     62191.0              [AMLODIPINE, METOPROLOL, SIMVASTATIN]
9     62217.0  [HYDROCHLOROTHIAZIDE, LISINOPRIL, POTASSIUM CH...
11    62221.0  [ALBUTEROL, HYDROCHLOROTHIAZIDE, LOSARTAN, MON...
12    62226.0  [AMLODIPINE, HYDROCHLOROTHIAZIDE, LISINOPRIL, ...
13    62228.0               [LISINOPRIL, METFORMIN, SIMVASTATIN]
...       ...                                                ...
2844  71882.0  [ALBUTEROL, FLUTICASONE NASAL, FLUTICASONE NASAL]
2846  71897.0  [HYDROCHLOROTHIAZIDE, LISINOPRIL, METFORMIN, S...
2847  71898.0  [SIMVASTATIN, HYDROCHLOROTHIAZIDE, LEVOTHYROXI...
2848  71901.0                [FUROSEMIDE, GLIPIZIDE, PREDNISONE]
2849  71902.0      [AMLODIPINE, HYDROCHLOROTHIAZIDE, METOPROLOL]

[1107 rows x 2 columns]

In [ ]:
# store to csv 
filtered.to_csv('/Users/karina/Documents/xplanar_placement/data/RXQ_RX_G.csv', index=False, sep=';')